<?xml version='1.0'?>
<ns2:test-suite xmlns:ns2='urn:model.allure.qatools.yandex.ru' start='1590744617934' stop='1590744678215'>
    <name>Test using Webdriverio</name>
    <title>Test using Webdriverio</title>
    <test-cases>
        <test-case start='1590744617936' status='broken' stop='1590744678212'>
            <name>Log into appplication</name>
            <title>Log into appplication</title>
            <labels>
                <label name='language' value='javascript'/>
                <label name='framework' value='wdio'/>
                <label name='thread' value='0-0'/>
            </labels>
            <parameters>
                <parameter kind='argument' name='browser' value='chrome'/>
            </parameters>
            <steps/>
            <attachments/>
            <failure>
                <message>Timeout of 60000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (C:\FaceBookMobiletestingwdio\specs\Test_runner.js)</message>
                <stack-trace>Error: Timeout of 60000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (C:\FaceBookMobiletestingwdio\specs\Test_runner.js)
                    at Test.Runnable._timeoutError (C:\FaceBookMobiletestingwdio\node_modules\mocha\lib\runnable.js:438:10)
                    at Timeout.&lt;anonymous> (C:\FaceBookMobiletestingwdio\node_modules\mocha\lib\runnable.js:242:24)
                    at listOnTimeout (internal/timers.js:549:17)
                    at processTimers (internal/timers.js:492:7)</stack-trace>
            </failure>
        </test-case>
    </test-cases>
</ns2:test-suite>